### ISSUE TITLE
Hangs on invalid urls

### ISSUE THREAD

**Issue by saschwarz** [jasonraimondi/url-to-png#18]
I'm using url-to-png to create snapshots in my Django web app for a database of web properties; some of which are no longer around.

If I invoke the docker image with this old and now defunked URL:
`http://localhost:3000/?url=http://www.greytdogsagility.com`

The container gives this error:
`error: Attempted to send payload of invalid type 'boolean'. Expected a string or Buffer.`

and the connection hangs "forever" and never times out.

**Comment by jasonraimondi** [comment]
Just pushed a fix for this in version 1.3.2 allowing the server to properly throw an error. I should probably just return a blank image or something, but that is a problem for another day.

**Comment by saschwarz** [comment]
Wow! Thank you for such a speedy resolution.
