### ISSUE TITLE
Browsers not being returned to pool on error?

### ISSUE THREAD

**Issue by saschwarz** [jasonraimondi/url-to-png#19]
I'm wondering if the browser needs to be returned to the pool if there is an exception? Should this line be in the `finally`?

https://github.com/jasonraimondi/url-to-png/blob/221817c9bd15ad411e2de5e09731b6f005219522/src/services/image-render.service.ts#L75

**Comment by jasonraimondi** [comment]
I believe you are correct, good find! If you want to submit a PR and become a contributor to the project I'd happily merge your contribution, otherwise it'll be at least till the EOD for me to get this tweaked.

**Comment by saschwarz** [comment]
I'll cut a PR. I was thinking it might be best to put another try/finally wrapping where the browser is taken from the pool so if any exception is raised it will always be released.

**Comment by jasonraimondi** [comment]
Thanks for the PR. I've merged and tagged this in v1.3.3
