### ISSUE TITLE
GitHub Sponsors is not on

### ISSUE THREAD

**Issue by Qapf** [jasonraimondi/url-to-png#21]
Thank you for making this straightforward tool. 

With it, I was able to get a [Visionect Place & Play 13](https://www.visionect.com/shop/place-play-13/) ePaper display to show reasonably complex & modern [sites](https://screen.transitapp.com/#/).

Please consider turning on [GitHub Sponsors](https://docs.github.com/en/sponsors). Things like this make the web go 'round.

**Comment by jasonraimondi** [comment]
I've added GH sponsor to the project, thank you for the suggestion and the kind words! I am glad you are finding the project useful!
