### ISSUE TITLE
Docker hub status check

### ISSUE THREAD

**Issue by AnnatarHe** [jasonraimondi/url-to-png#25]
Hi Jason,
I noticed that you have already made some changes on the master branch and have released at least 2 versions. However, the Docker Hub was not updated and the latest tag in Docker Hub is the image for arm devices.
Is this intentional?

**Comment by jasonraimondi** [comment]
Thanks for opening this issue and making me address the dockerhub build issue :) This is resolved here: https://github.com/jasonraimondi/url-to-png/commit/d3d068d18273957e2213d6ec3747b8e97a71e702


```
docker run --rm -p 3000:3000 ghcr.io/jasonraimondi/url-to-png
docker run --rm -p 3000:3000 ghcr.io/jasonraimondi/url-to-png:v1.4.2
```

**Comment by AnnatarHe** [comment]
@jasonraimondi 
Would you mind also uploading the images to Docker Hub?
Some areas, such as China, have difficulty accessing ghcr. Additionally, mirror sites only support Docker Hub.

I know some people don't like the docker company, but the docker hub is still the most famous docker images hub.🤣

**Comment by jasonraimondi** [comment]
@AnnatarHe This should be good to go now 👍
