### ISSUE TITLE
AWS environment variables names

### ISSUE THREAD

**Issue by enstyled** [jasonraimondi/url-to-png#29]
It would be great to follow [the naming conventions](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) for the AWS environment variables names, e.g.

`AWS_ACCESS_KEY_ID` instead of AWS_ACCESS_KEY
`AWS_SECRET_ACCESS_KEY` instead of AWS_SECRET_KEY
etc.

Many hosting services provide add-ons that will automatically inject the credentials and usually follow these naming conventions.

Additionally, adding support for `AWS_ENDPOINT_URL_S3` would be useful, in order to use S3-compatible services, such as Cloudlfare R2, Backblaze B2, Tigris.

**Comment by jasonraimondi** [comment]
I'd be happy to support this as long as there is backwards compatibility built in. If you submit a PR I would be happy to merge.
