### ISSUE TITLE
Bug: Incorrect resize when isFullPage=true and page height exceeds default

### ISSUE THREAD

**Issue by AnnatarHe** [jasonraimondi/url-to-png#43]
Hi @jasonraimondi , Thanks for your hard work, I think I found a bug in latest version.

when the url is like this `url-to-png.com/?url=xxx&isFullPage=true`, the resize method would resize the output image incorrectly.

i think is because the line below, when height or width not provided, it will use the default 1000px, but is wrong if the page's height is bigger than 1000.

https://github.com/jasonraimondi/url-to-png/blob/main/src/lib/image_render.ts#L69

<img width="597" alt="image" src="https://github.com/jasonraimondi/url-to-png/assets/8704175/927853e8-cc23-4bb4-b1ea-193dd8a45496">

**Comment by jasonraimondi** [comment]
Looking more like the weekend before I'll have time to get a fix in here. If you're able to make a PR in the meantime I'd happily verify and merge it

**Comment by jasonraimondi** [comment]
resolved in [v2.0.1](https://github.com/jasonraimondi/url-to-png/tree/v2.0.1)
