### ISSUE TITLE
Invalid response returned for some urls.

### ISSUE THREAD

**Issue by nagylzs** [jasonraimondi/url-to-png#6]
Here is an example. If I do a request like this:

```
http://localhost:5000/?url=https%3A%2F%2Ftest.localhost%2Ftest
```
Then I get HTTP 200 and Content-Type: image/png. But it actually returns the string "false".

[Request](https://imgur.com/yYosrkP)
[Response](https://imgur.com/Wx0kIaL)

You can see that the response has content-length: 5 so it cannot be a valid image. It contains the string "false". But the header says Content-Type: image/png and HTTP 200. This is messed up.

By the way, "test.localhost" is a non-existent domain. The original request to https://test.localhost/test cannot return a HTTP code, because test.localhost cannot be connected and so there is no request to make. But this should never return with HTTP 200.

**Comment by jasonraimondi** [comment]
Sorry I just never saw this or maybe I did and forgot, but anyways, this is fixed in 1.3.2
